// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsMathOps "github.com/acme-kuetix/acme-std-math/modules/math/ops/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["math/ops"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"math/ops"+"/"+"ops", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "ops", Impl: transitionsMathOps.NewOpsTransitions() }})
	}
}
